repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: debug-statements
      -   id: double-quote-string-fixer
      -   id: name-tests-test
      -   id: requirements-txt-fixer

  - repo: local
    hooks:
      - id: terraform-fmt
        name: terraform-fmt
        entry: terraform fmt -recursive -check
        language: system
        files: \.tf$
